### ISSUE TITLE
Data exported in SAV

### ISSUE THREAD

**Issue by bmalina** [onaio/onadata#1024]
Appropriately export data as string if text, numeric if integer/gps, select_one and select_multiple as the name/label in the choice options when exporting data in SAV.

**Comment by ukanga** [comment]
Seems the export is handled okay for string and numeric values including split GPS values, can you please clarify the instances this is not the case?

**Comment by msschroeder** [comment]
The export is working correctly. What Edwin was trying to get at were changes to how the data exports in a SAV exports.

In the meeting with Edwin, he mentioned that it would be better if:
- select_one and select_multiple variable types were determined by the name in the choice options (i.e. if the choices are 1 = Yes; 0 = No; 99 = Don't Know that field name will export as a numeric value instead of a string values; or if the choices are yes = Yes; no = No, dont_know = Don't Know that the field name will export as a string value)
- GPS (first column comes out as a string value). He said would be better if it came out as a numeric
- For the select_multiple, it comes out as 1st column with the choice options separated by a space (but this column cannot be used for analysis) and the other columns are the choice options in separate columns with TRUE/FALSE. However, it would be better if it used the name/label instead.
- Would prefer that note question types did not export

**Comment by ukanga** [comment]
- Made changes to have numeric values for select_one.
- For GPS, the split longitude, latitude, altitude and accuracy are already numeric
- For split select multiple, the type was string, now it is numeric/boolean, 1 and 0. I understand an SPSS script can be used to do this transformation in post processing, I will suggest that process for now.
- note columns have been removed from exports

**Comment by ukanga** [comment]
Seems I found a way to add the option `value_select_multiples` which will show the values of the select when split, for SPSS exports, the type of the column depends on whether the field value is numeric or not.
