### ISSUE TITLE
Support multiple bulk upload of CSV/Excel data to a form

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1422]
# Bulk data upload.

Allow bulk upload of data.

1. CSV upload to a blank form (already supported)
2. Excel upload to a blank form (not supported)
3. Allow multiple uploads of data to a form that may already include data.

Example XLSForm:

    | survey  |
    |         | type              | name    | label      |
    |         | text              | a_name  | Your Name? |
    |         | begin group       | fruits  | Fruits     |
    |         | select one fruits | fruit   | Fruit      |
    |         | end group         |         |            |
    |         |                   |         |            |
    | choices | list name         | name    | label      |
    |         | fruits            | mango   | Mango      |
    |         | fruits            | orange  | Orange     |
    |         | fruits            | apple   | Apple      |

## Excel bulk data upload to an existing form

A user should be able to upload an Excel `.xls/.xlsx` file to a form. The data in the file will be add new or edit submissions. The excel file should have:

1. The first row, the column header row, MUST HAVE the name that matches a question name in the XLSForm/XForm form. Any column name that does not match a question in the form will be ignored and hence not imported.
2. The column header names MAY HAVE group or repeat name separators. If there are no separators, it will be ASSUMED that the field name matches the question be it within a group or a repeat. For example:

    | a_name | fruits/fruit |
    | Alice  | mango        |
    | Bob    | orange       |

Without the group name, it will also match perfectly to the above form.

    | a_name | fruit  |
    | Alice  | mango  |
    | Bob    | orange |

3. There MUST NOT be a duplicate named column in the form or the data upload file otherwise it will be rejected.
4. The file MAY HAVE a `meta/instanceID` column which should uniquely identify a specific record. If present, the `meta/instanceID` will be used to identify whether the record is new or is an edit. If it does not exist, the system will create a new one for each new record added.

Questions:
1. What happens if an upload file has repeats?
2. Which Excel sheet should have the data imported?
3. Should an Excel template file be provided?

### Data upload expected behaviour

When the upload is complete, three things could happen to the data.

1. The upload will add new records to the existing form.
2. The upload will edit existing records where there is a matching `meta/instanceID` and add new records if the existing `meta/instanceID` is either blank or missing or does not exist.
3. The upload will overwrite existing records.

Note:

- For ANY approach, the UI should display a caution/warning, and a clear explanation of expected behaviour to the user.
- There will be the loss of the original data submitter information in the case of an overwrite.
- No effort will be made to link an exported file from Ona with the original submitter of the data.

#### 1. The upload will add new records to the existing form.

A data upload will add new records to the existing form under the following circumstances:

1. The form has NO submissions.
2. The upload file DOES NOT have the `meta/instanceID` column. (Should the user be allowed to specify a unique column?)

#### 2. The upload will edit existing records

A data upload will edit existing records in an existing form only if the upload file CONTAINS the column `meta/instanceID` and the value in this column MATCHES an existing record in the form.

Note: If the `meta/instanceID` is EITHER BLANK or MISSING or DOES NOT EXIST, a NEW record will be added to the form.

#### 3. The upload will OVERWRITE existing record

A data will OVERWRITE existing records if the parameter `overwrite` is `true`, `overwrite=true`, as part of the upload request. All existing records will be PERMANENTLY DELETED and the NEW data upload will become the new submissions in the form.

Questions:
- Should it be possible to REVERT this process? NO

## API implementation

Implement a `/api/v1/data/[pk]/import` or endpoint on the API.

### `POST` /data/[pk]/import

The endpoint will accept `POST` requests to upload the data CSV/Excel file.

- Persist the uploaded file in the database and file storage. I propose we use the `MetaData` model to keep this record; we may need to use a new key e.g. `data-imports` to refer to this files. New models could be used to achieve the same effect if there is more information to be stored.
- An asynchronous task will be created to start the process of importing the records from the file.

Request:

    POST /data/[pk]/import

    {
        "upload_file": ...,  // the file to upload
        "overwrite": false, // whether to overwrite or not, accepts true or false.
        ...
    }

Response:

    Response status code 201

    {
        "xform": [xform pk],
        "upload_id": [unique record identify for the upload]
        "filename": [filename of uploaded file]
    }

#### Processing the Uploaded file.

Depending on the query parameters, the data import will be taking into account the 3 options available as described above, i.e, NEW or EDIT or OVERWRITE.

- A record of the number of records processed, successful and failed should be maintained.
- In the event of a SUCCESS or a FAILURE, a notification SHOULD be sent. The notification can be via EMAIL to the user uploading the data or to via MQTT messaging/notifications or BOTH.

## Questions

1. What happens if an upload file has repeats?
2. Which Excel sheet should have the data imported?
3. Should an Excel template file be provided?
4. Should it be possible to REVERT this process? NO
5. How should we notify the user of upload status/progress?
6. What limits should we impose on data file uploads? in megabytes or number rows?
7. Is the process supposed to be atomic - i.e all uploads go through or partial uploads will do.
8. Should data imports from exports link the submitted by the user?
9. Should media links be downloaded into the new submission? Only data will be imported, media attachments will not be imported.

## Ref

- https://github.com/onaio/onadata/blob/export-import-features/docs/proposals/data-import.md

**Comment by msschroeder** [comment]
## Excel bulk data upload to an existing form
`There MUST NOT be a duplicate named column in the form or the data upload file otherwise it will be rejected.`

How will this work for duplicate names in different groups? This is supposedly possible?

Answers to questions:
`What happens if an upload file has repeats?`
I would assume that it would have to be formatted similar to CSV because all the data values would have to be on one page. @engwiri  What do you think?

`Which Excel sheet should have the data imported?`
I would vote the first sheet always.

`Should an Excel template file be provided?`
I would vote yes because this would simplify the process. But, it would have to be formatted similar to the CSV based on my previous comments

## Data upload expected behaviour
Question: Is the `meta/instanceID` a unique identifier?
Question: When a upload will add new records to an existing forms, were those or conditions (i.e. 1 or 2 can occur) or did both have to be met?

Questions:
`Should it be possible to REVERT this process? NO`
No, but a confirmation of action is a must. Should it be more than just a simple OK? @rowo @engwiri I would prefer yes, especially if the action cannot be undone.

## End Questions:
`How should we notify the user of upload status/progress?`
Yes, I would base it on percentages or number of records as that is a very tangible and easy for most people to understand.

`What limits should we impose on data file uploads? in megabytes or number rows?`
Ideally, I would say no, but what are the technical implications of not? @ukanga what is your recommendation for this question? If you would impose a limit, what would you use and how big? 

I would probably say size is what we tend to use most because it provide more context than number of rows on how big a file is. For example, a file could be 6 rows but a 1000 long and another 1000 rows but 500 column long, and both are the same size.

`Is the process supposed to be atomic - i.e all uploads go through or partial uploads will do.`
I would say partial uploads, and if not all go through, they can upload the file again similar to what you do in ODK Briefcase.

`Should data imports from exports link the submitted by the user?`
Yes, that way if there is a mistake, it can be determined who uploaded the data last.

`Should media links be downloaded into the new submission? Only data will be imported, media attachments will not be imported.` @ukanga This question is not very clear to me. What exactly are you asking? Should we include links from uploads?

**Comment by ukanga** [comment]
> There MUST NOT be a duplicate named column in the form or the data upload file otherwise it will be rejected.
> How will this work for duplicate names in different groups? This is supposedly possible?

I would expect in this case the column name will include the group name e.g `group_a/fruit`, in such a situation this would not be a duplicate.

**Comment by ukanga** [comment]
>What happens if an upload file has repeats?
I would assume that it would have to be formatted similar to CSV because all the data values would have to be on one page.

What about an Excel upload? Our Excel exports are not the same us our CSV exports.

**Comment by ukanga** [comment]
>Should media links be downloaded into the new submission? Only data will be imported, media attachments will not be imported. @ukanga This question is not very clear to me. What exactly are you asking? Should we include links from uploads?

Data upload would not support uploading image attachments i.e photo/video/signature/etc are not part of the upload. Only the text data is being imported.

**Comment by msschroeder** [comment]
> I would assume that it would have to be formatted similar to CSV because all the data values would have to be on one page.What about an Excel upload? Our Excel exports are not the same us our CSV exports.
> What happens if an upload file has repeats?

The Excel upload to have one worksheet would have all the columns you would expect a CSV export to have including how the repeats are formatted (i.e. group1/repeat[1]/name....group1/repeat[50]/name)

**Comment by msschroeder** [comment]
> Should media links be downloaded into the new submission? Only data will be imported, media attachments will not be imported. @ukanga This question is not very clear to me. What exactly are you asking? Should we include links from uploads?
> Data upload would not support uploading image attachments i.e photo/video/signature/etc are not part of the upload. Only the text data is being imported.

Yes, I think the links to the media files should be included in the submission. We will have to make this clear in the documentation that you cannot import media files with this upload method. But that would not be a use case for this feature.

**Comment by engwiri** [comment]
@ukanga @msschroeder I have carefully read through the descriptions and I think this is a great representation of whats needed. One of the outstanding questions that has come up more than once has to do with expected format of input. I think this would be solved using a template (Excel or CSV) and users would be required to follow the prescribed in that template (in addition to the help documentation). 

That way even if a user exports data in Excel in one format they may be required to reformat it to be able to upload it into the system. I think thats the quickest and cleanest way to solve the different ways in which data is represented. I think one approach makes sense.

I strongly agree with Megan's sentiments on the rest of the functionality, I do not feel I need to re-emphasise them. Please let me know if there are specific areas you need my input on.

**Comment by ukanga** [comment]
Implementation issue https://github.com/onaio/onadata/issues/1432.
