### ISSUE TITLE
Projects endpoint broken

### ISSUE THREAD

**Issue by WinnyTroy** [onaio/onadata#1518]
The `projects` endpoint is currently returning a 500 Error.

This occurs when trying to hit the endpoint using the api.

**Comment by WinnyTroy** [comment]
This occurs while trying to hit the endpoint from the browser

Attempts to access data from this endpoint using curl and the Zebra site are successful though.

**Comment by lincmba** [comment]
**Environment (production)**
works fine locally and stage

**Expected behaviour**
should return a json list of projects data
![image](https://user-images.githubusercontent.com/12713110/49780401-6aa7de80-fd1f-11e8-83cf-eae6ec6ebbb5.png)

**Actual behaviour**
Returns a 500 error
![image](https://user-images.githubusercontent.com/12713110/49780498-d5591a00-fd1f-11e8-8062-7e77700f0bc0.png)

**Sentry Exception**
 /api/v1/projects
`ImproperlyConfigured
Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.`
