### ISSUE TITLE
All export formats failing for hkibd form

### ISSUE THREAD

**Issue by Janemesi** [onaio/onadata#1634]
All export formats are failing for a specific form on HKI Bangladesh's account. The last submission was made 3 years ago. The form title is VMF_activity_monitoring_160303 under FAARM - Monitoring project.

When data is imported to a different account. All the export formats are prepared successfully. The current workaround is to uncheck **Split select multiple answers into separate columns** checkbox before preparing the exports.

**Comment by faith-mutua** [comment]
@Janemesi closing this issue. Turns out that exports on this form were failing because there is a **list_name** in the choices worksheet that is missing labels i.e. row 86. I added a dummy label to this row, then uploaded the form to my test account and submitted some data and exports were being generated fine even with the advanced export option **Split select multiple answers into separate columns** checked. 
I have advised the client to make the changes then replace the form and regenerate exports. I believe that they will work this time round.
