### ISSUE TITLE
ValueError: Invalid column index 18279

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1666]
https://sentry.onalabs.org/ona/onadata/issues/73465/

```
KeyError: 18279
  File "openpyxl/utils/cell.py", line 111, in get_column_letter
    return _STRING_COL_CACHE[idx]

ValueError: Invalid column index 18279
(5 additional frame(s) were not displayed)
...
  File "onadata/apps/viewer/tasks.py", line 144, in create_xls_export
    export_id, options)
  File "onadata/libs/utils/common_tools.py", line 176, in function_retry
    result = func(self, *args, **kwargs)
  File "onadata/libs/utils/export_tools.py", line 212, in generate_export
    total_records=total_records
  File "onadata/libs/utils/export_builder.py", line 872, in to_xls_export
    ws.append(headers)

ValueError: Invalid column index 18279
```

**Comment by WinnyTroy** [comment]
This issue seems to occur when creating exports in excel formats.

Excel has limits on the number of columns it can create when generating new xls files. 

The current form seems to exceed this limit while trying to export using xls format. This is when the `Split select multiple answers into separate columns` setting is set on the advanced export options settings provided when creating an export.

![xls_export](https://user-images.githubusercontent.com/11174326/65602312-58e0b080-dfac-11e9-8e9b-8995e5fabfca.png)

The current workaround is to turn off this setting in the advanced export options when trying to create an export for the form in question, in .xls format.

I was hoping to get some thoughts from the support team majorly..in regards to similar instances that may occur in future,
Would it be best to:
- Limit that setting in the case that an xlsx file contains more than, let's say, 100/150 choices defined in the choices sheet for all the select multiple questions within the form?
- Catch the exception and present a clear error message to the user(specifying that the choices provided in their choices sheet may be too many, and may exceed excel's limitation when creating exports.), in the case they have the option selected and their xls file contains select multiple questions with more than 100/150 choices for all select_multiple questions within the form

**Comment by WinnyTroy** [comment]
Closing this as it seems to not have occurred again.
Kindly re-open if this occurs again
