### ISSUE TITLE
Submission attachments list is not updated correctly after replacing an old image/file with a new one.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/onadata#1696]
### Environment (local, stage, preview, production)
All

### Expected behaviour

When an image/file in a submission is replaced, the old image/file should be replaced with the new one and deleted from the attachments list.

### Actual behaviour

The old image/file is replaced successfully but the old image/file is still retained in the attachments list.

### Steps to reproduce the behaviour

Use Enketo to edit a submission that has an attachment. Check the attachments for that submission and you will notice the previous attachment is still available.

---

### Implementation plan

- 
- 
-

**Comment by WinnyTroy** [comment]
The current implementation when editing submissions with new attachment files does not delete the old attachment, but creates a new attachment to the same submission alongside the old attachment files.

This could be helpful when keeping track of the submission history, however, as we never delete attachment files, this approach could fill up our storage unnecessarily.

@ukanga @pld @ivermac @JohnMwashuma @lincmba is there a different approach we could use, as in this instance when one edits a submission with a new media file?

**Comment by pld** [comment]
since this data is going in s3, and it's the way we're doing it now, I'm not particularly concerned about storage space.

If we can ignore attachments that are connected to submissions that are marked as deleted, would that be sufficient to address this error?

**Comment by JohnMwashuma** [comment]
So i found a way of filtering the attachments list from the submission api endpoint response. The response has the list of attachment fields with the attachment names. I used these names to filter the attachments.

**Comment by pld** [comment]
Does this issue affect exports or attachment downloads?

**Comment by JohnMwashuma** [comment]
yes it affects attachments, all attachments are downloaded even the ones that had been replaced.

**Comment by pld** [comment]
sounds like we need a general fix then that only surfaces attachments to instance that do have `deleted_at` set to null

**Comment by ukanga** [comment]
We may need to rethink this again - it will be more like we should not expose in any way the attachments that have been replaced. Hence the files/attachments endpoint should not expose these records at all. I like the idea of `deleted_at`, but I hesitate  exposing that information on the API at all since it would serve no purpose, the endpoint should use the field only to return attachments that are not replaced or deleted.

**Comment by pld** [comment]
Yes agree, that's how we use the `deleted_at` column in other tables

**Comment by WinnyTroy** [comment]
QA for this issue is proving to be abit tricky.
At the moment, deleting a submission cascade deletes all the attachments for the given submission.
However, when replacing the attachments in a submission from Enketo, we do not at any point interact with the AttachmentViewSet(And also the viewset is readonly), thus we do not trigger deletion of the replaced attachment.

After discussions with @DavisRayM  and @ivermac , we discussed catching this update, while saving the attachments to the instance on this file https://github.com/onaio/onadata/blob/3faabd335bff7e70d837bd4d9b1f2313d51def81/onadata/libs/utils/logger_tools.py#L217-L244
At this point we could check the existing attachments for that instance and compare with the list of media files received from the update request and call the soft_delete action to delete the replaced attachments.

**Comment by pld** [comment]
how would we compare with the list of media files received?

is this that if we replace an attachment for an instance, we'd only want to delete the existing attachment for that same field?

in that case is the check that we see if there's an existing attachment for the field we're replacing the attachment in, and delete that existing one if there is?

I'm trying to avoid a loop over all attachments if know specifically what attachments are relevant.

**Comment by WinnyTroy** [comment]
> is this that if we replace an attachment for an instance, we'd only want to delete the existing attachment for that same field?

We would be deleting existing attachments to an instance that have been replaced (i.e if they are no longer in the media files received with that instance). 
If the attachment is still present in the media files received, then it wasnt replaced, so those we wont delete.

> in that case is the check that we see if there's an existing attachment for the field we're replacing the attachment in, and delete that existing one if there is?

yes, this is what we had in mind.
We can identify new attachments for a submission as so: https://github.com/onaio/onadata/blob/3faabd335bff7e70d837bd4d9b1f2313d51def81/onadata/libs/utils/logger_tools.py#L354-L359

We can then identify the attachments that have been replaced and soft_delete those.
```code
replaced_attachments = [a for a in Attachment.objects.filter(instance=instance) 
                if a.media_file.name.split('/')[-1] not in media_files]
```

> I'm trying to avoid a loop over all attachments if know specifically what attachments are relevant.


True. Alternatively, we could use generator expressions as opposed to list comprehensions to filter these `replaced_attachments`, so that we dont load all the attachments to memory. This could be less expensive imo.

**Comment by pld** [comment]
This sounds good, let's pursue your final comment below and try to do this without a loop.

> True. Alternatively, we could use generator expressions as opposed to list comprehensions to filter these `replaced_attachments`, so that we dont load all the attachments to memory. This could be less expensive imo.

**Comment by WNjihia** [comment]
LGTM 🙂 
Tested that deleted attachments do not appear on the submissions attachments when replaced
Tested that deleted attachments do not appear on the submissions attachments when deleted and not replaced
Tested this for audio files too

**Comment by ivermac** [comment]
@WNjihia I think you want this comment and `QA+` label on the PR rather than the issue
