### ISSUE TITLE
Store `collected_at` datatime from ODK Submissions

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1723]
ODK submissions should be sending a `collected_at` field that contains a `datetime` representing when a Form was finalized. We should collect that information, store and display the information on our `data` endpoint, in order to facilitate validation on when the data was actually collected.

**Comment by DavisRayM** [comment]
@ukanga @ekigamba What do you think of this ?

**Comment by ukanga** [comment]
That depends, and perhaps what you are looking for are the `start`, `end`, `today` XForm metadata, see http://xlsform.org/en/#metadata, which are only present if the form author included them in the form. You should be looking at the corresponding field names for this in the JSON payload for a single submission. The metadata is collected when defined in the form.

**Comment by akahure** [comment]
Kaznet are looking to track only when it was collected since submission for the field offices can happen at anytime. The issue is that if we reject a submission based on submission time, this does not validate when the data was collected when they were actually in the field.

Question is, if we do this can we do it only for Kaznet and also what would be the implications around already submitted data and if a user commences data entry before the 'actual start time as added in the web, would we require a different validation setup for the time? @DavisRayM @ekigamba

**Comment by ukanga** [comment]
I think that will be a filter that Kaznet will have to use on its end, not pull any data that does not meet any of the conditions you have pointed out. We are like not going to validate that on the onadata side.

**Comment by DavisRayM** [comment]
This issue is being addressed on the `kaznet-web` side. Closing this issue, feel free to track the progress of the issue on `kaznet-web` [here](https://github.com/onaio/kaznet-web/issues/360).
