### ISSUE TITLE
Assign OwnerRole explicitly to and org creator

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1754]
### Environmental Information

- Operating System: all
- Onadata version: all
- Python version: 3

### Problem description

Not all OwnerRole permissions are assigned to the creator of an organization.

### Expected behaviour

Permissions like add a form to an organization should be assigned to org owners who create the organization.

### Steps to reproduce the behaviour

Create an organization and then try publishing a form using ODK Briefcase. You should get a 403 error message on the`/ formUpload` endpoint.

**Comment by DavisRayM** [comment]
Tried granting permissions to the `Owners` team but it seems the user will now encounter a `401`. Tested this on locally and on production.

Briefcase is making a request to `/formUpload` without authenticating.

**Comment by DavisRayM** [comment]
Investigated further noticed that Briefcase is not utilizing Django Digest to authenticate the user while pushing data. This may be an issue on our side related to the HEAD request, investigating further.

**Comment by DavisRayM** [comment]
_Info dump_

The `formUpload` endpoint is not properly initiating the Digest Authentication flow.

What should happen usually:

Client: Sends request to `/upload` with no auth credentials
Server: Returns a `401` with the Django Realm and other elements required to generate a partial digest
Client: Resends request to `/upload` with partial digest

Whats happening:
Client: Sends request to `/upload` with no auth credentials
Server: Return a `204` with OpenRosa Headers
Client: Assumes no authentication is required ??? And continues making request with no auth credentials.(This doesn't seem to be an issue on ODK Briefcase v1.12.1 as when it encounters the 401 when pushing it re-authenticates properly. v1.17.2 on the other hand doesn't _On my local atleast_ )

The [`DigestAuthentication` class](https://github.com/onaio/onadata/blob/master/onadata/libs/authentication.py#L93) should ideally handle this but seems to just be returning a `None` due to [this](https://github.com/onaio/onadata/blob/master/onadata/libs/authentication.py#L103).

@ukanga Do we need to return the `OpenRosa` headers ?

**Comment by DavisRayM** [comment]
> Tried granting permissions to the `Owners` team but it seems the user will now encounter a `401`. Tested this on locally and on production.
> 
> Briefcase is making a request to `/formUpload` without authenticating.

After further research I've managed to recreate the `403` error code on one of our servers. I'm unable to recreate the same issue locally (Works perfectly with ODK Briefcase v1.12.2 on my local even with most of the configurations on our server)
