### ISSUE TITLE
Filtering Pending review status data using API does not return correct data

### ISSUE THREAD

**Issue by samwata** [onaio/onadata#2112]
When I try to filter data that has "_review_status is null using API, it does not result to data that have pending status
using this query `https://api.ona.io/api/v1/data/form_id.json?query={"_review_status" : "3"}`  I get empty json 

Steps to replicate issue
- Turn on [review status](https://help.ona.io/knowledge-base/submission-review/) settings 
- Approve few records 
- Reject few records and leave others as pending
- Try to filter records with pending status

**Comment by DavisRayM** [comment]
This isn't a bug in most cases... The submission review functionality when turned on in `ona.io` doesn't actually create pending submission reviews. Unless the submission review has been reviewed before it's `_review_status` is technically `null` instead of `3` for the pending status.

If you'd like to get a list of "pending" reviews after the feature is turned on kindly try(_Not entirely sure if this query will work as expected but kindly try it out and let us know_):

`https://api.ona.io/api/v1/data/form_id.json?query={"_review_status" : null}`

Or:

`https://api.ona.io/api/v1/data/387184.json?query={"$or": [{"_review_status": "3"}, {"_review_status": null}]}`

**Comment by DavisRayM** [comment]
> `https://api.ona.io/api/v1/data/form_id.json?query={"_review_status" : null}`

Tested out the above query on a test branch and it seems the query doesn't work as intended. I'll suggest a few changes that will perhaps fix the issue
