### ISSUE TITLE
Add a way to perform search through all fields

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#2177]
## Suggested Feature / Enhancement

Currently search, as documented [here](https://ona.io/static/docs/data.html#example-iv) can only be done against a specific field at a time

**Comment by imkingrobi** [comment]
@DavisRayM Any comment on this as it is a blocker for https://github.com/onaio/zebra/issues/6699

**Comment by DavisRayM** [comment]
No comment from me at the moment; I'm just wondering how this search will be implemented? _We can search the submission XMLs and have a contains query but since it's the XML it might also search XML tags(Doesn't seem like it'll hurt to do so) as well as other considerations we might have to make in order to make this less heavy on the servers i.e pagination, handling sorting efficiently for records over a certain limit_

We could start looking into this for this current sprint though; Seems like a 2-3 day issue to me... maybe less

CC: @KipSigei

**Comment by imkingrobi** [comment]
@KipSigei @DavisRayM @FrankApiyo Can we have a meeting on it as it is blocking the following issue due this week? https://github.com/onaio/zebra/issues/6627

**Comment by imkingrobi** [comment]
@FrankApiyo  to research on the current frontend data view to guide on performance of the new data-view.

**Comment by FrankApiyo** [comment]
it seems when a request is made that looks as follows, search is carried out across all fields with sorted and paginated results
```https://api.ona.io/api/v1/data/540557.json?start=0&limit=100&sort={"_submission_time":1}&query=CXB3850052```

**Comment by FrankApiyo** [comment]
The pagination headers, however, don't seem to return the correct values. Will create a separate issue for this soon
