### ISSUE TITLE
Implement JSON schema endpoint for Ona Data

### ISSUE THREAD

**Issue by machariamuguku** [onaio/onadata#2352]
## Suggested Feature / Enhancement
Return form/submissions schema in [json schema format](https://json-schema.org/)

## Benefits of implementing the feature/enhancement
- The current schema endpoint (https://api.ona.io/api/v1/forms/[pk]/form.json) returns a convoluted schema type that needs parsing to be usable by connectors (airbyte, akuko, beam) and transformation tools (dbt) for data normalization. 
- This forces different tools that consume ona data to each implement this functionality differently
- Example parsing and implementation conversations:
	- [Ona data beam connector here](https://github.com/onaio/canopy/issues/1770)
	- [Airbyte here](https://github.com/onaio/canopy/issues/2949#issuecomment-1357193425)
	- [Akuko here](https://github.com/onaio/akuko-app/issues/1698)

- Having the API return a JSON schema type will help the API be readily pluggable to connectors and ease normalisation and validation implementation in transformation tools. This will also help maintain the no custom logic convention on ona data pipelines and transformers as well as simplify and streamline work for future connectors.

## Suggested implementation plan(Steps to be taken to implement feature)
- Translate form types at form creation to json schema type
- Store schema definitions statically (updated on form update)
- Provide json schema endpoint that returns this in JSON format

- Related to this https://github.com/onaio/onadata/issues/1296

**Comment by machariamuguku** [comment]
cc @alepietrobon

**Comment by alepietrobon** [comment]
Yes, i think this make life easier for everyone downstream. Thanks @machariamuguku 

@KipSigei , how do we get this scheduled? :)

**Comment by ukanga** [comment]
@machariamuguku @alepietrobon For historical context, the form representation at the `/api/v1/forms/<pk>/form.json` is not meant to be the JSON schema, it Is a direct JSON XForm representation of the form as implemented in [pyxform](https://github.com/XLSForm/pyxform/blob/master/pyxform/xform2json.py). In my opinion, it does have enough information within the context of XForm for someone to know what kind of data to expect.

Granted, we have considered supporting [JSON Schema](https://json-schema.org/) as attested by https://github.com/onaio/onadata/issues/1296. We did not pursue the path since this was sufficient enough for most users. I would recommend we either build a library that takes this XForm JSON and spits out a JSON Schema or add that support to the [pyxform codebase](https://github.com/XLSForm/pyxform) which is the source of the JSON data.

Note, beam uses the XForm XML and not the XForm JSON in conjunction with the [JavaRosa library](https://github.com/getodk/javarosa) to understand the data types of the form elements.

In not so many words, I mean to say @machariamuguku can pick this task and work on it. We may consider including it as an endpoint to the Ona Data API when we do have such a library or support in pyxform. It may not be a key priority item for this team at this time.

**Comment by machariamuguku** [comment]
Thanks @ukanga I'll look into it
