### ISSUE TITLE
SES Email Setup

### ISSUE THREAD

**Issue by hallahan** [onaio/onadata#785]
After setting up onadata, users cannot sign up, because it never sends out a verification email. We need instructions on how to set this up.

There is this beast of a document:

https://github.com/SEL-Columbia/formhub/wiki/How-To-Run-Your-Own-Formhub-Instances-on-Amazon-Web-Services

**Comment by dalekunce** [comment]
Updated the local_settings.py with the AWS credentials then rebooted and SES still doesn't seem to be working. 

Weird that I'm getting the SES error message from AWS as described in the formhub docs.

**Comment by dalekunce** [comment]
Saga with SES continues.

Installed ses using:
```bash
source ~/.virtualenvs/onadata/bin/activate
pip install -r onadata/requirements/ses.pip --allow-all-external
```

getting a 403 error: "CSRF token missing or incorrect."

<img width="1155" alt="screen shot 2015-08-12 at 5 14 45 pm" src="https://cloud.githubusercontent.com/assets/1913857/9239946/c61ab5ea-4115-11e5-9cbb-b6346c8aa0a9.png">

**Comment by dalekunce** [comment]
@mberg any idea about the latest stoping point for this.

**Comment by denniswambua** [comment]
@dalekunce 
Have you added the below parameters to your local_settings file?

`EMAIL_BACKEND = 'django_ses.SESBackend'`

`AWS_ACCESS_KEY_ID = 'your access key'`

`AWS_SECRET_ACCESS_KEY = 'your secret key'`

`AWS_SES_REGION_NAME = 'your region'`

`AWS_SES_REGION_ENDPOINT = 'and this too'`

**Comment by mberg** [comment]
@dalekunce - did this work for you?

**Comment by dalekunce** [comment]
Getting the following error after updating the local_settings file and creating a new user.

CSRF verification failed. Request aborted.

<img width="1148" alt="screen shot 2015-08-17 at 10 17 19 am" src="https://cloud.githubusercontent.com/assets/1913857/9312108/9529b798-44cf-11e5-9463-208abc78e162.png">

**Comment by denniswambua** [comment]
Ensure if you have overriden this `MIDDLEWARE_CLASSES` in your local_setting file to include this `'django.middleware.csrf.CsrfViewMiddleware'`.
Visit this link for more info https://docs.djangoproject.com/en/dev/ref/csrf/

Also check if your browser is accepting cookies.

note:
I have been able to install onadata and setup the SES on a VM using the above steps.

**Comment by denniswambua** [comment]
@dalekunce 
Kindly share your local_setting.py

Here is the one i am using http://pastebin.com/NSqH3Fjk

**Comment by dalekunce** [comment]
adding the line 

```bash
MIDDLEWARE_CLASSES = 'django.middleware.csrf.CsrfViewMiddleware'
```

makes the site return a 502 error

<img width="350" alt="screen shot 2015-08-18 at 4 20 11 pm" src="https://cloud.githubusercontent.com/assets/1913857/9345377/08ccec10-45c5-11e5-88df-1f3967a859ee.png">

here is my local_setting.py 
https://gist.github.com/dalekunce/38f9e635ada019472238

**Comment by pld** [comment]
What do you see in the error and access logs when that happens?

Usually that error means the reverse proxy (Nginx) cannot connect to the
downstream server (Ona).

**Comment by dalekunce** [comment]
@pld where are the logs you are looking for. nginx?

**Comment by denniswambua** [comment]
Set this as the MIDDLEWARE_CLASSES

`MIDDLEWARE_CLASSES = (
    'onadata.libs.profiling.sql.SqlTimingMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
    'onadata.libs.utils.middleware.LocaleMiddlewareWithTweaks',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.transaction.TransactionMiddleware',
    'onadata.libs.utils.middleware.HTTPResponseNotAllowedMiddleware',
    'readonly.middleware.DatabaseReadOnlyMiddleware',
)`

**Comment by dalekunce** [comment]
@denniswambua added the above and am still getting the 502 error

**Comment by mberg** [comment]
Dale - are you running zebra lite too?

Sometimes I get a similar error when I'm logged into zebra then switch to
ona.io.

**Comment by dalekunce** [comment]
Running whatever was on the ami. Assuming that is just onadata.

**Comment by hallahan** [comment]
It's only onadata

**Comment by ukanga** [comment]
An nginx 502 means the upstreami process that nginx is connectiing to is down. And in this case the onadata uwsgi process iw down, you need to check on that.

Look at the onadata uwsgi log, this should be what you configured in the `logto` [uwsigi.ini](https://github.com/onaio/onadata/blob/master/uwsgi.ini#L15)

If there is an error in the logfile it would give you a hint of what is wrong.

if not you can try and make sure that you have fully stopped the uwsgi process, something in the vain of `sudo stop onadata` and then run the uwsgi process in the foreground - something in the vain of `uwsgi --inii uwsgi.ini --env DJANGO_SETTINGS_MODULE=onadata.settings.common `. You may need to run the command as the user you run the onadata process as.

Any errors that are shown would be helpful in letting you know where the problem is, my guess at this moment is since the `local_settings.py` is being updated, there is something wrong with it or even a syntax error in the file.

You should be aware, any time you change the settings file, you will have to restart the onadata uwsgi service/process.

If the above does not work, I can send you py public key and I can check this with you over `ssh+tmux/screen` session.

**Comment by ukanga** [comment]
You will need to comment the `logto=` line in your `uwsgi.ini` to run `uwsgi` in the foreground.

**Comment by DavisRayM** [comment]
@ukanga Can we safely close this ?
