### ISSUE TITLE
Dynamic selects from pre-loaded data not working with Enketo

### ISSUE THREAD

**Issue by rgaudin** [onaio/onadata#806]
Dynamic selects with `search()` does not work on Enketo although Enketo says it's supported.
It does work on ODK Collect so pretty sure it's not a survey error.

Is this an ONA deployment issue? Is there a way to know what version of enketo-express is used on ONA?

cc @MartijnR @mberg

**Comment by mberg** [comment]
Martijn won't support search in enketo he's opposed to the way it's
implemented in ODK.  So we have to figure out a work around

**Comment by MartijnR** [comment]
Yes, it's ridiculous how it's done... (Note that in Enketo you can probably do this with built-in XPath functions in a choice-filter. However this won't pass ODK Validate.)

The version number used can be seen here: https://enketo.ona.io/

**Comment by rgaudin** [comment]
Yeah I got confused with the `pulldata()` one.
I've seen the enkteo-only `select_one_from_file` and it looks really good but I noticed the thread has been silent for a year. Anyone working on implementing it in Collect?

What would be the reasonable way to move forward?
Also, barely related, is there a `property()` that would allow run-time to know whether on Enketo or Collect?

**Comment by mberg** [comment]
We would fully support trying to get a fix for this

Martijn ideas on how we can realistically move forward?

**Comment by MartijnR** [comment]
select_one_from_file would be step 1 of the way forward. I know @dorey started with this, but it has not been a priority for KoBo. 

step 2 would be to build a replacement for ODK Validate (Enketo Validate or OpenRosa validate) or have someone dive into javarosa to create a custom ODK Validate build with additional functions. This would give us most of the search() functionality in choice-filters. Though ODK core developers try not to touch javarosa (hence we know have the search() appearance), I'd think that adding support for starts-with, ends-with etc, would be quite straightforward. Looking further into the future, a new validator is still a more efficient way forward though, as we could add complex functions such as [randomize() for itemsets](https://github.com/kobotoolbox/enketo-express/issues/363).

step 3 would be to add any missing functions, which would be very easy in Enketo

There is no official way to detect whether Enketo or ODK Collect is used. However, you could use one of the properties that enketo cannot support, such as imei. Enketo's value will be something like `"no simserial property in enketo"`. Btw, the property() function is also not supported in Enketo, because it's not an XPath function (no XML to query). However, this could be added by internally creating an XML instance that contains the properties.

**Comment by mberg** [comment]
dickson thoughts?

**Comment by ukanga** [comment]
It is a matter of willing to dive into javarosa code and maintain a fork of the ODK Validate or starting on Enketo Validate and have a pyxform version that makes use of this specific version. I remember before `area()` was adopted Ona used a custom ODK Validate with it's pyxform fork.

**Comment by MartijnR** [comment]
Yes, that would the matter for step 2. Eventually we'll get stuck with this approach though when we want to add more complex stuff. (Apparently javarosa is so fragile even [major bugs](https://groups.google.com/forum/#!topic/opendatakit-developers/nN8HTA5pUIM) apparently cannot be fixed (such as this one). In that case, we could a) let the new functions pass in the custom ODK Validate without actually implementing them, or b) build a new validator around Enketo's engine.
