### ISSUE TITLE
Unmantained and facing deprecation.

### ISSUE THREAD

**Issue by qlands** [onaio/onadata#808]
It's been 8 months since the last github activity of the admins and the project is too useful to go to waste. Besides the deprecation warning could mean the end of it.

Any volunteers to maintain the project going forward? Otherwise I would take it.

**Comment by qlands** [comment]
The current code does not even work!!! The storage of submissions moved from Mongo to Postgres but all the ended up broken....Sad to see how such a good project takes a bad direction. Anyway... I saved the code before Ona chopped it up into pieces! I will post it in a new repository with a new name.

**Comment by qlands** [comment]
OK. So after few hours refactoring and cleaning up the code and by exercising the rights of the BSD license I created [FormShare](https://github.com/qlands/FormShare). This is based on the commit https://github.com/onaio/onadata/commit/21f21f0e7b2d7f745173f7957375a9d96c2a065e  (Thu Mar 12 08:45:09 2015 -0400) just before the implementation of Open Street Map (OSM) and a lot of changes that chopped up the code leaving the legacy of FormHub in the limbo. From here we will cherry-pick specific commits particularity the implementation of OSM. I am now moving all the CGIAR implementations of OnaData to FormShare. If you fancy to contribute to FormShare please drop me an email. Cheers and keep good free software free

**Comment by siemvaessen** [comment]
Hi @qlands - is Formshare similar to OnaData?

**Comment by pld** [comment]
hi @qlands and @siemvaessen, we really appreciate your interest in OnaData. The current code does in fact work, I'm not sure if the install instructions are detailed enough, but I do know of other groups that are using this code base to run OnaData installations. The exports do also work and the move away from MongoDB has let us scale this to much larger projects, but again the install instructions may lack detail to easily get this up and running.

We are really sorry about the problems you are seeing running this code. We wish we could spend more time focusing only on this, but to make sure we'll be around to support this code in the future we've had to devote a lot of time to working with our clients and building a sustainable business. We've had to make some hard decisions in the past year and unfortunately not being able to work on this code base was one of them, we understand this sucks, and again, we're sorry. We believe this puts in the position to better support this project going forward.

But... we have some good news! We are in the process of shifting a large amount of new code open source. We are cleaning up the code base and plan to make it public within the next couple of months. This code will have some big changes, including significant performance improvements to the submission pipeline.

Once this is done we'll remove the deprecation notice. We erred on the side of caution and added that notice because at the time we didn't know what our future was going to look like and thought it would be unfair to send the wrong message to organizations that decided to use this software.

**Comment by qlands** [comment]
Hi @siemvaessen. Formshare is based on OnaData from the commit 21f21f0 (Thu Mar 12 08:45:09 2015 -0400). You can use it as a drop down replacement from OnaData. Sorry @pld but OnaIO left the code totally broken and was not because of installations instructions. Droping MongoDB is just silly since it provided high levels of scalability and interoperability (by using JSON).... Nevertheless the legacy of FormHub continues in FormShare

**Comment by qlands** [comment]
Just one comment @siemvaessen : Formshare differs from OnaData in:  FormShare is not intended as a software as service where you register, pay subscriptions, etc. Is for organizations to install it in their own servers or cloud infrastructure so they can collect their own data. So you can install it in your own servers using Docker for example and start collecting data.

**Comment by pld** [comment]
@qlands That's simply not true, http://whodcp.org/, is running based on this OnaData code with a different template (the code supports modular templates). KoboForm is also based on this codebase, https://github.com/kobotoolbox/koboform/. There are also a number of other local groups that run off of this code base.

Your comment about MongoDB is also incorrect and doesn't fit our use case and the use cases of a lot of groups we work with. Postgres supports JSON at the database level and with ACID guarantees on consistency. MongoDB is unable to provide ACID guarantees, you can find more deatils here https://aphyr.com/posts/284-jepsen-mongodb and for Postgres consistency here, https://aphyr.com/posts/282-jepsen-postgres. When running production projects at country-level scale it's essential we don't suffer data loss. There are a number of Formhub and successor installations that had varying levels of data-loss because of complications keeping MongoDB in sync with the Postgres data store. Using JSON in Postgres gives us all the benefits on MongoDB's query language (we wrap traditional Mongo queries at the API level and convert them to Postgres) without the lack of consistency and maintenance overhead, it's a big improvement.

**Comment by pld** [comment]
@siemvaessen another interesting alternative to Formhub based tools is [Dokomo Forms](https://github.com/SEL-Columbia/dokomoforms) from SEL at Columbia, where Formhub first started.

**Comment by qlands** [comment]
It simple: You clone the code, you follow the instructions (as much as possible), you send some submissions, try to do an export and bingo! Does not work... You do the same with commit  21f21f0  and it works. And then you end up trying to figure it out why it does not work.... But not more argument.... You continue your way.... FormShare its way...

**Comment by jasonrogena** [comment]
@qlands did you see this? -> https://news.ycombinator.com/item?id=11857674
